connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.warehouse=dtcc_catalog

# OAuth2 Authentication for Polaris
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=root:s3cr3t
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
iceberg.rest-catalog.oauth2.server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens

# Storage access (Garage S3)
fs.s3.enabled=true
s3.endpoint=http://garage:3900
s3.region=garage
s3.path-style-access=true
s3.aws-access-key=GK135da1acc67448e5f988c2d9
s3.aws-secret-key=8ebd487cc54261411c33d336465f8a26ba58c064bddb3c56692189b2b4a21eba
